// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as Core from "@material-ui/core"

function make(head, headRow) {
  return React.createElement(Core.TableHead, {
    children: React.createElement(
      Core.TableRow,
      {
        children: null,
        className: headRow,
      },
      React.createElement(Core.TableCell, {
        children: "Reference",
      }),
      React.createElement(Core.TableCell, {
        children: "Other Genes Mentioned",
      }),
    ),
    className: head,
  })
}

export { make }
/* react Not a pure module */
