// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Core = require("@material-ui/core")

function PublicationTableHead(Props) {
  return React.createElement(Core.TableHead, {
    children: React.createElement(
      Core.TableRow,
      {
        children: null,
      },
      React.createElement(Core.TableCell, {
        children: "Reference",
      }),
      React.createElement(Core.TableCell, {
        children: "Other Genes Mentioned",
      }),
    ),
  })
}

var make = PublicationTableHead

exports.make = make
/* react Not a pure module */
