// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as Core from "@material-ui/core"
import * as SkeletonWithCount$DictyGenomepage from "../../components/SkeletonWithCount.bs.js"

function make(param) {
  return React.createElement(
    "div",
    {
      role: "loader",
    },
    React.createElement("br", undefined),
    React.createElement(Core.Box, {
      children: React.createElement(SkeletonWithCount$DictyGenomepage.make, {
        count: 10,
      }),
    }),
  )
}

export { make }
/* react Not a pure module */
