// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as Core from "@material-ui/core"

function make(param) {
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(Core.TableCell, {
      children: "Reference",
    }),
    React.createElement(Core.TableCell, {
      children: "Other Genes Mentioned",
    }),
  )
}

export { make }
/* react Not a pure module */
