// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Core = require("@material-ui/core")
var SkeletonWithCount$DictyGenomepage = require("../../components/SkeletonWithCount.bs.js")

function make(param) {
  return React.createElement(
    "div",
    {
      role: "loader",
    },
    React.createElement("br", undefined),
    React.createElement(Core.Box, {
      children: React.createElement(SkeletonWithCount$DictyGenomepage.make, {
        count: 10,
      }),
    }),
  )
}

exports.make = make
/* react Not a pure module */
