// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Core = require("@material-ui/core")
var SkeletonWithCount$DictyGenomepage = require("./SkeletonWithCount.bs.js")

function Loader(Props) {
  return React.createElement(
    "div",
    {
      role: "loading",
    },
    React.createElement(
      Core.Box,
      {
        children: null,
      },
      React.createElement(SkeletonWithCount$DictyGenomepage.make, {
        count: 10,
      }),
      React.createElement("br", undefined),
      React.createElement("br", undefined),
      React.createElement(SkeletonWithCount$DictyGenomepage.make, {
        count: 10,
      }),
      React.createElement("br", undefined),
      React.createElement("br", undefined),
      React.createElement(SkeletonWithCount$DictyGenomepage.make, {
        count: 10,
      }),
      React.createElement("br", undefined),
      React.createElement("br", undefined),
      React.createElement(SkeletonWithCount$DictyGenomepage.make, {
        count: 5,
      }),
    ),
  )
}

var make = Loader

exports.make = make
/* react Not a pure module */
