// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as Core from "@material-ui/core"
import * as SkeletonWithCount$DictyGenomepage from "./SkeletonWithCount.bs.js"

function Loader(Props) {
  return React.createElement(
    Core.Box,
    {
      children: null,
    },
    React.createElement(SkeletonWithCount$DictyGenomepage.make, {
      count: 10,
    }),
    React.createElement("br", undefined),
    React.createElement("br", undefined),
    React.createElement(SkeletonWithCount$DictyGenomepage.make, {
      count: 10,
    }),
    React.createElement("br", undefined),
    React.createElement("br", undefined),
    React.createElement(SkeletonWithCount$DictyGenomepage.make, {
      count: 10,
    }),
    React.createElement("br", undefined),
    React.createElement("br", undefined),
    React.createElement(SkeletonWithCount$DictyGenomepage.make, {
      count: 5,
    }),
  )
}

var make = Loader

export { make }
/* react Not a pure module */
