// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as Belt_Array from "rescript/lib/es6/belt_Array.js"
import * as Skeleton$MuiLab from "rescript-material-ui-lab/src/Skeleton.bs.js"
import * as Lab from "@material-ui/lab"

function SkeletonWithCount(Props) {
  var count = Props.count
  return React.createElement(
    "div",
    undefined,
    Belt_Array.makeBy(count, function (i) {
      return React.createElement(Lab.Skeleton, {
        animation: Skeleton$MuiLab.Animation.wave,
        key: String(i),
      })
    }),
  )
}

var make = SkeletonWithCount

export { make }
/* react Not a pure module */
