// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Belt_Array = require("rescript/lib/js/belt_Array.js")
var Skeleton$MuiLab = require("rescript-material-ui-lab/src/Skeleton.bs.js")
var Lab = require("@material-ui/lab")

function SkeletonWithCount(Props) {
  var count = Props.count
  return React.createElement(
    "div",
    undefined,
    Belt_Array.makeBy(count, function (i) {
      return React.createElement(Lab.Skeleton, {
        animation: Skeleton$MuiLab.Animation.wave,
        key: String(i),
      })
    }),
  )
}

var make = SkeletonWithCount

exports.make = make
/* react Not a pure module */
